server:
  port: 8801
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://root:chibao07032001@localhost:27017/USER?authSource=admin

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
